let languagesObject = {
  en: {
    auth: {
      appTitle: "domino",
      appComment: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      pageTitle: "Domino - Sign in",
      signIn: "Sign in",
      userLabel: "User",
      userFeed: "Please enter your user name.",
      passwordLabel: "Password",
      passwordFeed: "Please enter your password.",
      passwordRemember: "Remember me",
      logIn: "Log in",
      forgotPassword: "Forgot password?",
      createNewAccount: "Create new account",
    },
    register: {
      appTitle: "domino",
      appComment: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      pageTitle: "Domino - Register",
      cardTitle: "Create a Domino account",
      firtsName: "Firts Name",
      firtsNameFeed: "Please enter your firts name",
      lastName: "Last Name",
      lastNameFeed: "Please enter your last name",
      email: "Email",
      emailFeed: "Please enter your email",
      phone: "Phone",
      phoneField: "Please enter your phone",
      userName: "Username",
      userNameFeed: "Please enter your username",
      password: "Password",
      passwordFeed: "Please enter your password",
      confirm: "Confirm",
      confirmFeed: "Please confirm your password",
      showPassword: "Show password",
      register: "Register",
      logIn: "Log in"
    },
    header: {
      title: "Domino",
      logOutTitle: "Log Out",
      logOutText: "Are you sure you want to log out?",
      confirmButtonText: "Yes",
      cancelButtonText: "No"
    },
    footer: {
      help: "Help",
      privacy: "Privacy",
      term: "Terms",
    }
  },
  es: {
    auth: {
      appTitle: "dominó",
      appComment: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      authTitle: "Dominó - Autentificar",
      signIn: "Autentificar",
      userLabel: "Usuario",
      userFeed: "Por favor entre su nombre de usuario.",
      passwordLabel: "Contraseña",
      passwordFeed: "Por favor entre su contraseña.",
      passwordRemember: "Recordarme",
      logIn: "Iniciar sesión",
      forgotPassword: "¿ Olvidaste la Contraseña ?",
      createNewAccount: "Crear cuenta nueva",
    },
    register: {
      appTitle: "dominó",
      appComment: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      pageTitle: "Dominó - Registrarse",
      cardTitle: "Crea una cuenta en Dominó",
      firtsName: "Nombre",
      firtsNameFeed: "Por favor entre su Nombre",
      lastName: "Apellidos",
      lastNameFeed: "Por favor entre sus apellidos",
      email: "Correo",
      emailFeed: "Por favor entre su cuenta de correo",
      phone: "Teléfono",
      phoneField: "Por favor entre su número de teléfono.",
      userName: "Nombre de Usuario",
      userNameFeed: "Por favor entre su Nombre de usuario.",
      password: "Contraseña",
      passwordFeed: "Por favor teclee su contraseña.",
      confirm: "Confirmar",
      confirmFeed: "Por favor confirme su contraseña.",
      showPassword: "Mostrar Contraseña",
      register: "Registrarte",
      logIn: "Iniciar sesión"
    },
    header: {
      title: "Dominó",
      logOutTitle: "Cerrar Sesión",
      logOutText: "Esta seguro que desea cerrar la sesión ?",
      confirmButtonText: "Sí",
      cancelButtonText: "No",
    },
    footer: {
      help: "Ayuda",
      privacy: "Privacidad",
      term: "Codiciones",
    }
  },
};

export default languagesObject;
